<?php	global $request;	?>


<a href="<?php	echo(htmlspecialchars($request->MakeLink(null,'add')));	?>">Add User</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('organization','add')));	?>">Add Organization</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('add_payment')));	?>">Add Payment</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('pending')));	?>">View Pending Membership Applications</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('membership_types')));	?>">Add/Edit Membership Types</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('membership_email')));	?>">Change Notifications for Membership Applications</a>
<a href="<?php	echo(htmlspecialchars($request->MakeLink('form_settings')));	?>">Enable or Disable Forms</a>