<?php

	global $request;
	
	
	$org=$this->org;
	
	$render=function ($label, $key) use ($org) {
	
		?><div><div><?php
			echo(htmlspecialchars($label));
		?>:</div><div><?php
			echo(htmlspecialchars($org->$key));
		?></div></div><?php
	
	}

?>


<div class="object_display">

	<?php
	
		$render('Organization ID','id');
		$render('Name','name');
		$render('Address','address1');
		$render('Address (Continued)','address2');
		$render('City','city');
	
	?>
	
	<div>
	
		<div>Province/State &amp; Country:</div>
		
		<div><?php
			echo(
				htmlspecialchars(
					(is_null($org->territorial_unit) || ($org->territorial_unit===''))
						?	$org->country
						:	$org->country.' - '.$org->territorial_unit
				)
			);
		?></div>
	
	</div>
	
	<?php	$render('Postal/Zip Code','postal_code');	?>
	
	<div>
	
		<div>Web Address:</div>
		
		<div><a href="<?php
			echo(htmlspecialchars($org->url));
		?>"><?php
			echo(htmlspecialchars($org->url));
		?></a></div>
	
	</div>
	
	<?php
	
		$render('Phone','phone');
		$render('Fax','fax');
	
	?>
	
	<div>
	
		<div>Type:</div>
		
		<div><?php	echo(htmlspecialchars($this->type));	?></div>
	
	</div>
	
	<h2>Primary Contact Information</h2>
	
	<?php
	
		$render('Name','contact_name');
		$render('Title','contact_name');
		$render('E-Mail','contact_email');
		$render('Phone','contact_phone');
		$render('Fax','contact_fax');
	
	?>
	
	<h2>Secondary Contact Information</h2>
	
	<?php
	
		$render('Name','secondary_contact_name');
		$render('Title','secondary_contact_name');
		$render('E-Mail','secondary_contact_email');
		$render('Phone','secondary_contact_phone');
		$render('Fax','secondary_contact_fax');
	
	?>

</div>

<?php	require(WHERE_TEMPLATES.'org_users.phtml');	?>