<!doctype html>

<html xmlns="http://www.w3.org/1999/xhtml">
	
	<body>
	
		<p>
			Server
			<b><?php	echo(htmlspecialchars($_SERVER['COMPUTERNAME']));	?></b>
			experienced
			a<?php	if (isset($this->error)):	?> <b><?php	echo(htmlspecialchars($this->error));	?></b><?php	else:	?>n<?php	endif;	?>
			<?php	if (isset($this->error_desc)):	?><b>(<?php	echo(htmlspecialchars($this->error_desc));	?>)</b><?php	endif;	?>
			error occurred during a
			<b><?php	echo(htmlspecialchars($_SERVER['REQUEST_METHOD']));	?></b>
			request for
			<b><?php
			
				$url='http';
				
				if (
					isset($_SERVER['HTTPS']) &&
					($_SERVER['HTTPS']!=='off')
				) $url.='s';
				
				$url.='://';
				
				$url.=isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
				
				if (
					isset($_SERVER['SERVER_PORT']) &&
					(intval($_SERVER['SERVER_PORT'])!==80)
				) $url.=':'.$_SERVER['SERVER_PORT'];
				
				$url.=$_SERVER[
					isset($_SERVER['HTTP_X_ORIGINAL_URL'])
						?	'HTTP_X_ORIGINAL_URL'
						:	'REQUEST_URI'
				];
				
				echo(htmlspecialchars($url));
				
			?></b>
			
		</p>
		
		<p>This request was handled by the script <b><?php	echo(htmlspecialchars($_SERVER['SCRIPT_FILENAME']));	?></b></p>
		
		<?php	if (isset($this->desc)):	?>
		
		<p>A description of the problem was given:</p>
		
		<p><b><?php	echo(htmlspecialchars($this->desc));	?></b></p>
		
		<?php	endif;	?>
	
		<?php
		
			function output_arr (&$arr) {
			
				if (count($arr)===0):
				
		?>
		
		<p><i>Empty</i></p>
		
		<?php
		
					return;
				
				endif;
			
				ksort($arr);
			
		?>
		
		<table border="1" style="border-collapse:collapse;" cellpadding="3">
		
			<thead>
			
				<tr>
				
					<td><b>Key</b></td>
					<td><b>Value</b></td>
				
				</tr>
			
			</thead>
		
			<tbody>
		
				<?php	foreach ($arr as $key=>$value):	?>
				
				<tr>
				
					<td><?php	echo(htmlspecialchars($key));	?></td>
					<td><?php	echo(htmlspecialchars($value));	?></td>
					
				</tr>
				
				<?php	endforeach;	?>
				
			</tbody>
		
		</table>
		
		<?php	}	?>
		
		<h2>GET</h2>
		<?php	output_arr($_GET);	?>
		
		<h2>COOKIES</h2>
		<?php	output_arr($_COOKIE);	?>
		
		<h2>SESSION</h2>
		<?php	output_arr($_SESSION);	?>
		
		<h2>POST</h2>
		<?php	output_arr($_POST);	?>
		
		<h2>SERVER</h2>
		<?php	output_arr($_SERVER);	?>
	
	</body>

</html>