<?php	global $request;	?>

<script type="text/javascript">

	function verify_form () {
	
		var verified=true;
		<?php	echo($this->form->RenderVerify());	?>
		return verified;
	
	}

</script>


<?php	if (isset($this->intro) && (count($this->intro)!==0)):	?>

<div class="intro">

	<?php	foreach ($this->intro as $x):	?>
	<p><?php	echo(htmlspecialchars($x));	?></p>
	<?php	endforeach;	?>

</div>

<?php	endif;	?>


<?php	if (isset($this->messages) && (count($this->messages)!==0)):	?>

<div class="messages">

	<?php	foreach ($this->messages as $message):	?>
	
	<div><?php	echo(htmlspecialchars($message));	?></div>
	
	<?php	endforeach;	?>

</div>

<?php	endif;	?>


<?php

	if (isset($this->top_links) && (count($this->top_links)!==0))
	foreach ($this->top_links as $url=>$label):
	
?>

<div class="top_link"><a href="<?php	echo(htmlspecialchars($url));	?>"><?php	echo(htmlspecialchars($label));	?></a></div>

<?php	endforeach;	?>


<?php	echo($this->form->Render());	?>


<script type="text/javascript">

	AddCallbackToEvent(
		document.getElementById('form'),
		'onsubmit',
		verify_form
	);
	
	var terr_unit=document.getElementById('form').elements['territorial_unit'];
	
	if (!(
		(terr_unit===null) ||
		(terr_unit===undefined)
	)) AddCallbackToEvent(
		terr_unit,
		'onchange',
		function () {
		
			var obj=document.getElementById('form').elements['territorial_unit'];
		
			document.getElementById('form').elements['territorial_unit_other'].style.display=
				(obj.options[obj.selectedIndex].value==='')
					?	'block'
					:	'none';
			
		}
	);

</script>