<?php	global $request;	?>


<p>You must login to continue</p>

<form method="post" action="?<?php

	foreach ($_GET as $key=>$value) if (!(($key===LOGIN_KEY) || ($key===LOGOUT_KEY))) echo(htmlspecialchars(rawurlencode($key).'='.rawurlencode($value).'&'));
	
	echo(htmlspecialchars(rawurlencode(LOGIN_KEY).'='.rawurlencode(TRUE_STRING)));

?>">

	<?php	if (isset($this->message)):	?>
	<p><?php	echo(htmlspecialchars($this->message));	?></p>
	<?php	endif;	?>

	<div>
		
		<div>Username:</div>
		<div><input type="text" name="<?php	echo(htmlspecialchars(USERNAME_KEY));	?>" /></div>
		
	</div>
	
	<div>
	
		<div>Password:</div>
		<div><input type="password" name="<?php	echo(htmlspecialchars(PASSWORD_KEY));	?>" /></div>
		
	</div>
	
	<div>
	
		<div>Remain Logged In:</div>
		<div><input type="checkbox" name="<?php	echo(htmlspecialchars(REMEMBER_ME_KEY));	?>" value="<?php	echo(htmlspecialchars(TRUE_STRING));	?>" /></div>
	
	</div>
	
	<input type="submit" name="Login" value="Login" />
	
	<div><a href="<?php	echo(htmlspecialchars($request->MakeLink('forgot_password')));	?>">Forgot your password?</a></div>

</form>
