<p>You must login to continue</p>

<form method="post" action="?<?php	echo(htmlspecialchars(rawurlencode(LOGIN_KEY)));	?>=<?php	echo(htmlspecialchars(rawurlencode(TRUE_STRING)));	?>">

	<?php	if (isset($this->message)):	?>
	<p><?php	echo(htmlspecialchars($this->message));	?></p>
	<?php	endif;	?>

	<div>
		
		<div>Username:</div>
		<div><input type="text" name="<?php	echo(htmlspecialchars(USERNAME_KEY));	?>" /></div>
		
	</div>
	
	<div>
	
		<div>Password:</div>
		<div><input type="password" name="<?php	echo(htmlspecialchars(PASSWORD_KEY));	?>" /></div>
		
	</div>
	
	<input type="submit" name="Login" value="Login" />

</form>