<?php

	global $request;
	global $header;
	global $user;
	global $title;
	global $display_payment_prompt;
	global $top_menu;

?><!doctype html>


<html xmlns="http://www.w3.org/1999/xhtml">


	<head>
	
		<meta http-equiv="content-type" content="application/xhmtl+xml; charset=UTF-8" />
		
		<title>
		
			MISA BC
			<?php	if (!is_null($title)):	?>
			- <?php	echo(htmlspecialchars($title));	?>
			<?php	endif;	?>
		
		</title>
		
		<link rel="stylesheet" type="text/css" href="https://www.civicinfo.bc.ca/style/reset.css" />
		<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C400%2C300&ver=3.5.1" />
		<link rel="stylesheet" type="text/css" href="<?php
		
			echo(
				htmlspecialchars(
					$request->MakeFileLink(
						array(
							WHERE_STYLESHEETS,
							'main.css'
						)
					)
				)
			);
		
		?>" />
		
		<script type="text/javascript" src="<?php
		
			echo(
				htmlspecialchars(
					$request->MakeFileLink(
						array(
							WHERE_JAVASCRIPT,
							'shared.js'
						)
					)
				)
			);
		
		?>"></script>
		
		<?php	foreach ($header as $x) echo($x);	?>
	
	</head>
	
	
	<body>
	
		<div id="header" style="background-image: url(<?php
		
			mt_srand();
			
			$bgs=array(
				$request->MakeFileLink(
					array(
						'images',
						'slide2.jpg'
					)
				),
				$request->MakeFileLink(
					array(
						'images',
						'winter.png'
					)
				)
			);
			
			if (count($bgs)!==0) echo($bgs[mt_rand(0,count($bgs)-1)]);
		
		?>);">
		
			<div id="banner">
			
				<?php	if (!is_null($user)):	?>
				<div id="user_area">Hello, <?php	echo(htmlspecialchars($user->Name('F L')));	?> [ <a href="<?php	echo(htmlspecialchars($request->MakeLink(null,null,array('logout' => TRUE_STRING))));	?>">Logout</a> ]</div>
				<?php	endif;	?>
			
				<a href="http://devel.misa.bc.ca/"><img src="<?php
				
					echo(
						htmlspecialchars(
							$request->MakeFileLink(
								array(
									'images',
									'logo.png'
								)
							)
						)
					);
				
				?>" /></a>
				
				<div>
				
					<a href="http://devel.misa.bc.ca/news/">News</a>
					|
					<a href="http://www.misa.bc.ca/">Newsletter</a>
					|
					<a href="http://www.misa.bc.ca/">Careers</a>
					|
					<a href="http://www.misa.bc.ca/">Contact Us</a>
				
				</div>
			
			</div>
			
			<div id="page_title">
			
				Municipal Information Systems Association of BC
				
				<?php	if (!is_null($user) && ($user->type==='admin')):	?>
				
				<div id="keyword_search">
				
					<form method="get" action="<?php	echo(htmlspecialchars($request->MakeLink('keyword')));	?>">
					
						<input type="text" name="keywords" />
						
						<input type="submit" name="search" value="Search" />
					
					</form>
				
				</div>
				
				<?php	endif;	?>
			
			</div>
			
			<div id="top_nav">
			
				<?php	foreach ($top_menu as $label=>$url):	?>
				<a href="<?php	echo(htmlspecialchars($url));	?>"><?php	echo(htmlspecialchars($label));	?></a>
				<?php	endforeach;	?>
				
			</div>
			
		
		</div>

		<?php	if (isset($display_payment_prompt) && $display_payment_prompt):	?>
		<div class="notification">You may pay membership dues, <a href="<?php
		
			echo(
				htmlspecialchars(
					$request->MakeLink(
						'payment'
					)
				)
			);
		
		?>">click here</a> to do so</div>
		<?php	endif;	?>

		
		<div id="main_container">
		
			<?php	if (!is_null($user)):	?>
			<div id="sidebar">
			
				<div>
				
					<h1>Navigation</h1>
				
					<a href="<?php	echo(htmlspecialchars($request->MakeLink()));	?>">My Profile</a>
					
					<?php	if (!is_null($user->organization)):	?>
					<a href="<?php	echo(htmlspecialchars($request->MakeLink('organization',$user->organization->id)));	?>">My Organization</a>
					<?php	endif;	?>
					
					<?php	if ($user->type==='admin'):	?>
					<a href="<?php	echo(htmlspecialchars($request->MakeLink('users')));	?>">Users</a>
					<a href="<?php	echo(htmlspecialchars($request->MakeLink('organizations')));	?>">Organizations</a>
					<a href="<?php	echo(htmlspecialchars($request->MakeLink('administration')));	?>">Administration</a>
					<?php	endif;	?>
				
				</div>
			
			</div>
			<?php	endif;	?>
			
			<div id="main"<?php	if (!is_null($user)):	?> class="with_sidebar"<?php	endif;	?>>
			
				<?php	if (!is_null($title)):	?>
				<h1><?php	echo(htmlspecialchars($title));	?></h1>
				<?php	endif;	?>
			
				<?php	$this->template->Render($this->file);	?>
			
			</div>
			
		</div>
		
		<div id="footer">
		
			<div>Copyright &copy; <?php	echo(htmlspecialchars(date('Y')));	?> MISA BC</div>
			<div><a href="http://devel.misa.bc.ca/privacy-policy/">Privacy Policy</a></div>
		
		</div>
	
	</body>


</html>