<?php	global $request;	?>


<h1>Notes</h1>


<div class="top_link"><a href="<?php
	echo(
		htmlspecialchars(
			$request->MakeLink(
				'note',
				array(
					'add',
					$this->org->id
				)
			)
		)
	);
?>">Add Note</a></div>


<div class="no_results"<?php	if (count($this->notes)!==0):	?> style="display:none;"<?php	endif;	?>>No notes</div>


<table>

	<thead>
	
		<tr>
		
			<td>Name</td>
			<td>Date</td>
			<td>Text</td>
		
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	foreach ($this->notes as $note):	?>
		
		<tr>
		
			<td class="nowrap">
			
				<?php	if (is_null($note->modified_by)):	?>
				<strong>Unknown</strong>
				<?php	else:	?>
				<a href="<?php
					echo(
						htmlspecialchars(
							$request->MakeLink(
								null,
								$note->modified_by->id
							)
						)
					);
				?>"><?php	echo(htmlspecialchars($note->modified_by->Name('F L')));	?></a>
				<?php	endif;	?>
				
			</td>
			
			<td class="nowrap">
			
				<a href="<?php
					echo(
						htmlspecialchars(
							$request->MakeLink(
								'note',
								$note->id
							)
						)
					);
				?>"><?php	echo(htmlspecialchars($note->modified->format('j/n/Y g:i:s A')));	?></a>
			
			</td>
			
			<td>
			
				<?php
				
					preg_match_all(
						'/^(.*)$/mu',
						$note->text,
						$matches
					);
					
					foreach ($matches[1] as $match):
					
						$match=MBString::Trim($match);
					
						?><p><?php
						
							if ($match===''):
							
								?>&nbsp;<?php
								
							else:
							
								echo(htmlspecialchars($match));
								
							endif;
							
						?></p><?php
					
					endforeach;
				
				?>
			
			</td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>

</table>