<?php

	global $request;
	global $user;
	
?>


<h1>Users</h1>

<?php	if (($user->type==='admin') || ($user->org_id===$this->org->id)):	?>

<div class="top_link"><a href="<?php	echo(htmlspecialchars($request->MakeLink(null,'add')));	?>">Add User</a></div>

<?php	endif;	?>

<?php	if (count($this->users)===0):	?>

<div class="no_results">No users</div>

<?php	else:	?>

<table>

	<thead>
	
		<tr>
		
			<td>Last Name</td>
			<td>First Name</td>
			<td>Type</td>
		
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	foreach ($this->users as $x):	?>
		
		<tr>
		
			<?php	$link=htmlspecialchars($request->MakeLink(null,$x->id));	?>
		
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('L')));	?></a></td>
			
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('F')));	?></a></td>
			
			<td><?php
			
				switch ($x->type) {
				
					case 'user':
					default:
					
						echo(htmlspecialchars('User'));
						break;
						
					case 'superuser':
					
						echo(htmlspecialchars('Organization Admin'));
						break;
						
					case 'admin':
					
						echo(htmlspecialchars('Sitewide Admin'));
						break;
				
				}
			
			?></td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>

</table>

<?php	endif;	?>