<?php	global $request;	?>


<table>

	<thead>
	
		<tr>
		
			<td>Name</td>
			<td>City</td>
			<td>Province/State</td>
			<td>Country</td>
			<td>Type</td>
		
		</tr>
		
	</thead>
	
	<tbody>
	
		<?php	foreach ($this->results as $x):	?>
		
		<tr>
		
			<?php	$link=htmlspecialchars($request->MakeLink('organization',$x->id));	?>
		
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->name));	?></a></td>
			
			<td><?php	echo(htmlspecialchars($x->city));	?></td>
			
			<td><?php	echo(htmlspecialchars($x->territorial_unit));	?></td>
			
			<td><?php	echo(htmlspecialchars($x->country));	?></td>
			
			<td><?php	echo(htmlspecialchars($x->membership_type));	?></td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>
	
</table>