<?php
	
	global $request;
	global $user;
	
?><h1>Payment Information</h1>

<?php	if ($user->type==='admin'):	?>

<div class="top_link"><a href="<?php	echo(htmlspecialchars($request->MakeLink('add_payment')));	?>">Add Payment</a></div>

<?php	endif;	?>

<?php	if (count($this->payment_info)===0):	?>

<div class="no_results">No payments</div>

<?php	else:	?>

<table>

	<thead>
	
		<tr>
	
			<td>Date</td>
			<td>Type</td>
			<td>Subtotal</td>
			<td>Tax</td>
			<td>Total</td>
			<td>Paid</td>
			
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	$format='M j, Y';	?>
	
		<?php	foreach ($this->payment_info as $x):	?>
		
		<tr>
		
			<td><?php
			
				$admin_link=false;
				$superuser_link=false;
				
				if ($user->type==='admin') $admin_link=true;
				else if (
					($user->type==='superuser') &&
					$x['paid']->GetValue()
				) $superuser_link=true;
				
				if ($admin_link || $superuser_link):
			
			?><a href="<?php
			
				echo(
					htmlspecialchars(
						$admin_link
							?	$request->MakeLink(
									'edit_payment',
									$x['id']->GetValue()
								)
							:	$request->MakeLink(
									'recipt',
									$x['id']->GetValue()
								)
					)
				);
			
			?>"><?php
			
				endif;
				
				echo(htmlspecialchars($x['created']->GetValue()->format($format)));
				
				if ($superuser_link || $admin_link):
				
			?></a><?php	endif;	?></td>
			<td><?php
			
				$type_str='';
				switch ($x['type']->GetValue()) {
				
					case 'membership new':
						$type_str='New';
						break;
					case 'membership renewal':
						$type_str='Renewal';
						break;
					case 'sponsor':
						$type_str='Sponsorship';
						break;
					case 'conference':
						$type_str='Conference';
						break;
					case 'other':
					default:
						$type_str='Other';
						break;
				
				}
				
				echo(htmlspecialchars($type_str));
				
			?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['subtotal']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['tax']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['total']->GetValue())));	?></td>
			<td><?php	echo(htmlspecialchars(($x['paid']->GetValue()===0) ? 'No' : 'Yes'));	?></td>
			
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>
	
</table>

<?php	endif;	?>