<?php
	
	global $request;
	global $user;
	
?><h1>Payment Information</h1>

<?php	if (count($this->payment_info)===0):	?>

<div class="no_results">No payments</div>

<?php	else:	?>

<table>

	<thead>
	
		<tr>
	
			<td>Date</td>
			<td>Type</td>
			<td>Subtotal</td>
			<td>Tax</td>
			<td>Total</td>
			<td>Paid</td>
			
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	$format='M j, Y';	?>
	
		<?php	foreach ($this->payment_info as $x):	?>
		
		<tr>
		
			<td><?php
			
				$link=false;
				if (
					(
						($user->type==='superuser') ||
						($user->type==='admin')
					) &&
					$x['paid']->GetValue()
				):
				
					$link=true;
			
			?><a href="<?php
			
				echo(
					htmlspecialchars(
						$request->MakeLink(
							'receipt',
							$x['id']->GetValue()
						)
					)
				);
			
			?>"><?php
			
				endif;
				
				echo(htmlspecialchars($x['created']->GetValue()->format($format)));
				
				if ($link):
				
			?></a><?php	endif;	?></td>
			<td><?php
				
				echo(
					htmlspecialchars(
						($x['type']->GetValue()==='membership new')
							?	'New'
							:	'Renewal'
					)
				);
				
			?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['subtotal']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['tax']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['total']->GetValue())));	?></td>
			<td><?php	echo(htmlspecialchars(($x['paid']->GetValue()===0) ? 'No' : 'Yes'));	?></td>
			
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>
	
</table>

<?php	endif;	?>