<?php	global $request;	?>


<form method="POST">

	<table>

		<thead>
		
			<td>Name</td>
			<td>City</td>
			<td>Province/State</td>
			<td>Country</td>
			<td>Type</td>
		
		</thead>
		
		<tbody>
		
			<?php	foreach ($this->results as $x):	?>
			
			<tr>
				
				<td><a href="<?php	echo(htmlspecialchars($request->MakeLink('organization',$x->id)));	?>"><?php	echo(htmlspecialchars($x->name));	?></a></td>
				
				<td><?php	echo(htmlspecialchars($x->city));	?></td>
				
				<td><?php	echo(htmlspecialchars($x->territorial_unit));	?></td>
				
				<td><?php	echo(htmlspecialchars($x->country));	?></td>
				
				<td><?php	echo(htmlspecialchars($x->membership_type));	?></td>
				
				<td><button type="submit" name="<?php	echo(htmlspecialchars($x->id));	?>" class="approve_organization" value="approve">Approve</button></td>
				
				<td><button type="submit" name="<?php	echo(htmlspecialchars($x->id));	?>" class="approve_organization" value="delete">Delete</button></td>
				
			</tr>
				
			<?php	endforeach;	?>
		
		</tbody>
		
	</table>
	
</form>


<script type="text/javascript">

	var approve_organization=document.getElementsByClassName('approve_organization');
	for (var i=0;i<approve_organization.length;++i) {
		
		var e=approve_organization[i];
		if (e.value==='approve') AddCallbackToEvent(
			e,
			'onclick',
			function () {
			
				return confirm('Are you sure you want to approve this user?');
			
			}
		);
		else if (e.value==='delete') AddCallbackToEvent(
			e,
			'onclick',
			function () {
			
				return confirm('Are you sure you want to delete this user?');
			
			}
		);
		
	}
		
	
	

</script>