<?php	global $request;	?>

<script type="text/javascript">

	function verify_form () {
	
		var verified=true;
		<?php	echo($this->form->RenderVerify());	?>
		return verified;
	
	}

</script>


<?php	echo($this->form->Render());	?>


<script type="text/javascript">

	AddCallbackToEvent(
		document.getElementsByTagName('form')[0],
		'onsubmit',
		verify_form
	);
	
	AddCallbackToEvent(
		document.getElementsByTagName('form')[0].elements['territorial_unit'],
		'onchange',
		function () {
		
			var obj=document.getElementsByTagName('form')[0].elements['territorial_unit'];
		
			document.getElementsByTagName('form')[0].elements['territorial_unit_other'].style.display=
				(obj.options[obj.selectedIndex].value==='')
					?	'block'
					:	'none';
			
		}
	);

</script>

<?php	if (isset($this->users)):	?>

<h1>Users</h1>

<table>

	<thead>
	
		<tr>
		
			<td>Last Name</td>
			<td>First Name</td>
			<td>Type</td>
		
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	foreach ($this->users as $x):	?>
		
		<tr>
		
			<?php	$link=htmlspecialchars($request->MakeLink(null,$x->id));	?>
		
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('L')));	?></a></td>
			
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('F')));	?></a></td>
			
			<td><?php
			
				switch ($x->type) {
				
					case 'user':
					default:
					
						echo(htmlspecialchars('User'));
						break;
						
					case 'superuser':
					
						echo(htmlspecialchars('Organization Admin'));
						break;
						
					case 'admin':
					
						echo(htmlspecialchars('Sitewide Admin'));
						break;
				
				}
			
			?></td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>

</table>

<?php	endif;	?>

<?php	if (isset($this->payment_info)):	?>

<h1>Payment Information</h1>

<table>

	<thead>
	
		<tr>
	
			<td>Date</td>
			<td>Type</td>
			<td>Subtotal</td>
			<td>Tax</td>
			<td>Total</td>
			<td>Paid</td>
			
		</tr>
	
	</thead>
	
	<tbody>
	
		<?php	$format='M j, Y';	?>
	
		<?php	foreach ($this->payment_info as $x):	?>
		
		<tr>
		
			<td><?php	echo(htmlspecialchars($x['created']->GetValue()->format($format)));	?></td>
			<td><?php
				
				echo(
					htmlspecialchars(
						($x['type']->GetValue()==='membership new')
							?	'New'
							:	'Renewal'
					)
				);
				
			?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['subtotal']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['tax']->GetValue())));	?></td>
			<td>$<?php	echo(htmlspecialchars(sprintf('%.2f',$x['total']->GetValue())));	?></td>
			<td><?php	echo(htmlspecialchars(($x['paid']->GetValue()===0) ? 'No' : 'Yes'));	?></td>
			
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>
	
</table>

<?php	endif;	?>