<table>

	<thead>
	
		<td>Last Name</td>
		<td>First Name</td>
		<td>Organization</td>
		<td>Type</td>
	
	</thead>
	
	<tbody>
	
		<?php	foreach ($this->results as $x):	?>
		
		<tr>
		
			<?php	$link=htmlspecialchars($request->MakeLink(null,$x->id));	?>
			
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('L')));	?></a></td>
			
			<td><a href="<?php	echo($link);	?>"><?php	echo(htmlspecialchars($x->Name('F')));	?></a></td>
			
			<td>
			
				<?php	if (is_null($x->organization)):	?>
				&nbsp;
				<?php	else:	?>
				<?php	echo(htmlspecialchars($x->organization->name));	?>
				<?php	endif;	?>
			
			</td>
			
			<td><?php
			
				switch ($x->type) {
				
					case 'user':
					default:
						
						echo(htmlspecialchars('User'));
						break;
						
					case 'superuser':
					
						echo(htmlspecialchars('Organization Admin'));
						break;
						
					case 'admin':
					
						echo(htmlspecialchars('Sitewide Admin'));
						break;
				
				}
			
			?></td>
		
		</tr>
		
		<?php	endforeach;	?>
	
	</tbody>

</table>